<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<ApplicationIcon>Logo/logoappli.ico</ApplicationIcon>	  
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Images\**" />
    <EmbeddedResource Remove="Images\**" />
    <None Remove="Images\**" />
    <Page Remove="Images\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Logo\logoappli.ico" />
    <None Remove="Logo\logosae1.ico" />
    <None Remove="Police\arial.ttf" />
    <None Remove="Police\PlayfairDisplay-Bold.ttf" />
    <None Remove="Police\PlayfairDisplay-Italic.ttf" />
    <None Remove="Police\PlayfairDisplay-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\EpicurAPP-Partage\EpicurAPP-Partage\EpicurAPP-Partage.csproj" />
	<PackageReference Include="itext" Version="9.4.0" />
	<PackageReference Include="itext.bouncy-castle-adapter" Version="9.4.0" />
	<PackageReference Include="itext7" Version="9.4.0" />
	<PackageReference Include="LiveCharts.Wpf.Core" Version="0.9.8" />
	<PackageReference Include="System.Net.Http.Json" Version="9.0.10" />
	<PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Police\arial.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Logo\logoappli.ico" />
    <Resource Include="Police\PlayfairDisplay-Bold.ttf" />
    <Resource Include="Police\PlayfairDisplay-Italic.ttf" />
    <Resource Include="Police\PlayfairDisplay-Regular.ttf" />
    <Resource Include="Logo\logosae1-bgremove.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="App.xaml" />
  </ItemGroup>

</Project>
